# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - /Users/omatrot/Documents/etp_web:/etp_web

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/usr/local/var/mysql
        environment:
            MYSQL_ROOT_PASSWORD: knhGxQHUify7
            MYSQL_DATABASE: etp
            MYSQL_USER: test
            MYSQL_PASSWORD: knhGxQHUify7
